### ISSUE TITLE
Use ecto schemas

### ISSUE THREAD

**Issue by a3kov** [PJUllrich/lemon_ex#1]
Instead of structs you can use [embedded Ecto schemas](https://hexdocs.pm/ecto/3.9.4/embedded-schemas.html). I recently used that with another API and it worked great. Can both validate the request before sending it to the provider, and parse data coming from webhooks. Nested types after casting are proper structs (schemas) instead of maps so in the application code it's very easy to match on type.
When a schema can nest multiple schema types. consider using [polymorphic_embed](https://github.com/mathieuprog/polymorphic_embed)
Cherry on top: use [typed_ecto_schema](https://github.com/bamorim/typed_ecto_schema) and generate typespecs automatically!

**Comment by PJUllrich** [comment]
@a3kov great suggestion, thank you! I'll get back to this probably only in May, but PRs are most appreciated :)

**Comment by a3kov** [comment]
I am not yet using the library, but planning to (LS looks really promising but my project is not yet at a stage where I am ready to accept payments). Would be happy to help/collaborate when I get the time!
Btw, I discovered LS thanks to your library, so thank you for that :smile:
