### ISSUE TITLE
`Subscription` missing key `first_subscription_item`

### ISSUE THREAD

**Issue by samrat** [PJUllrich/lemon_ex#10]
Hello,

The key `first_subscription_item` is missing as it is not parsed out in the Subscription module. 

I'm new to the LemonSqueezy API but it seems like it's necessary for extracting the price. (https://docs.lemonsqueezy.com/guides/tutorials/nextjs-saas-billing#syncing-subscription-data)

**Comment by PJUllrich** [comment]
@samrat I just released `v0.2.2` which now includes that field. Could you test it please?
