### ISSUE TITLE
Best way to handle webhooks when using LiveView

### ISSUE THREAD

**Issue by ricksonoliveira** [PJUllrich/lemon_ex#11]
This issue is more to get a vision of what you guys usually do when using this package to handle LS webhooks with LiveView.

Since the [`handle_event/1`](https://github.com/PJUllrich/lemon_ex/blob/main/lib/lemon_ex/webhooks/handler.ex#L2) handler from the package doesn't receive a connection as a param - Do you guys use something like GenServer, or PubSub to broadcast a message to your live view and redirect the user to your app, for example, or to manage user interaction?

If someone has examples of use cases for their webhook modules that would like to share,

Thanks!

**Comment by PJUllrich** [comment]
I usually use PubSub to notify the LiveView that something has changed (e.g. the subscription status). You can pass redirect URLs to LS and it will redirect the user to the page after a checkout is complete. So, on that page, you could show a loading spinner with "Processing your payment" and then listen for any PubSub events coming through. However, you have to handle the case that the event has already come in before the user opens the page and you start listening for PubSub events. So, I always query the record when I mount the LiveView to check whether it has already changed/been created and only then I start listening for events. An easier solution would just to query the record every few seconds. That's usually fine too if you don't have millions of users.
