### ISSUE TITLE
Timeout from Lemon Squeezy - enable way to pass options

### ISSUE THREAD

**Issue by edborsa** [PJUllrich/lemon_ex#6]
Some times whenever I am doing an HTTP call to lemon squeeze it takes longer than 5 seconds.
There is not way for me to configure timeout of the request.

**Comment by PJUllrich** [comment]
Hey, I just released a new version `0.1.6` which allows you to add `request_options` to the `lemon_ex` config. Could you try that and let me know if it works, please? I added an example to the Readme.
